CREATE DATABASE `dbload` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'dbload'@'localhost' IDENTIFIED BY 'dbload';
CREATE USER 'dbload'@'%' IDENTIFIED BY 'dbload';

REVOKE ALL PRIVILEGES ON * . * FROM 'dbload'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'dbload'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON dbload. * TO 'dbload'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON dbload. * TO 'dbload'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;
